/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  Frontend: [
    {
      type: 'autogenerated',
      dirName: '.'
    },

    {
      type: 'link',
      label: 'Github',
      href: 'https://yanadev.github.io/'
    },
    {
      type: 'link',
      label: 'CSDN',
      href: 'https://blog.csdn.net/VOID_Pointer_G'
    },
    {
      type: 'link',
      label: '掘金',
      href: 'https://juejin.cn/user/3263006244083678'
    }
  ]
}
