/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  docSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: '博客源码',
      href: 'https://github.com/yanadev/yanadev.github.io'
    },
    {
      type: 'link',
      label: 'CSDN',
      href: 'https://blog.csdn.net/VOID_Pointer_G'
    },
    {
      type: 'link',
      label: '掘金',
      href: 'https://juejin.cn/user/3263006244083678'
    }
  ]
}

export default sidebars
